server:
  port: 8004
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.viki.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: 123456789
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                      # 等待连接获取的最大超时时间
   cloud:
     consul:
       host: 10.101.12.43
       port: 1234
       enable: true
       discovery:
               enabled: true
               instanceId: ${spring.application.name}-${spring.cloud.consul.host}-${spring.cloud.consul.port}
               serviecName: ${spring.application.name}
               health-check-interval: 5s
               healthCheckPath: /health
               preferIpAddress: true


